### PR TITLE
Updated refractor dependency and bumped version

### PR DESCRIPTION
**Pull request by sunknudsen**
See https://github.com/wooorm/refractor/releases/tag/3.3.0 and https://github.com/PrismJS/prism/releases/tag/v1.23.0

### CODE REVIEW

**Comment by sunknudsen** [comment]
Hey @rexxars, some Prisim [issues](https://github.com/PrismJS/prism/releases/tag/v1.23.0) have been fixed upstream. Have a moment to merge this in and publish to npm?

**Comment by rexxars** [comment]
Sure. Strictly speaking this shouldn't be necessary as the version range is wide enough - reinstalling dependencies should upgrade to the latest version of refractor automatically. But I'll bump to include some of the other lockfile warnings currently open.

**Comment by rexxars** [comment]
Published as v2.1.4

**Comment by sunknudsen** [comment]
@rexxars, thanks!

> Strictly speaking this shouldn't be necessary as the version range is wide enough - reinstalling dependencies should upgrade to the latest version of refractor automatically.

True... well, I clearly still have a lot to learn.

Have an amazing day!

**Pull request merged**
